apiVersion: virtualkubelet.liqo.io/v1alpha1
kind: VirtualNode
metadata:
  name: vn1
spec:
  clusterIdentity:
    clusterID: a50a605a-f2b1-454e-a0b7-1a7328abc0f4
    clusterName: cluster2
  offloadingPatch: {}
  template:
    spec:
      selector:
        matchLabels:
          virtual-node: vn1
      template:
        spec:
          containers:
            - name: virtual-kubelet
              image: localhost:5001/virtual-kubelet
  createNode: true
  kubeconfigSecretRef:
    name: test-ref
  images: []
  resourceQuota:
    hard:
      limits.cpu: "4"
      limits.memory: 4Gi
      requests.cpu: "2"
      requests.memory: 2Gi
  labels: {}
  storageClasses: []
  